version: '3'
services:
  db:
    image: 'postgres:latest' 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: buscabelo
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  app:
      container_name: buscabelo-api
      restart: always
      build: .
      volumes:
        - .:/usr/src/app
      ports:
          - "3000:3000"
      depends_on:
          - db
  nginx:
      build:
        context: ./nginx
      container_name: nginx
      hostname: nginx
      ports:
        - "80:80" 
      depends_on:
        - app
      networks:
        - buscabelo-net
networks:
  buscabelo-net:
    external: true
